/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SuperRouteImport } from './routes/super'
import { Route as GymsRouteImport } from './routes/gyms'
import { Route as FoodRouteImport } from './routes/food'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperTenantsRouteImport } from './routes/super.tenants'
import { Route as SuperSystemRouteImport } from './routes/super.system'
import { Route as SuperFeaturesRouteImport } from './routes/super.features'
import { Route as SuperBillingRouteImport } from './routes/super.billing'
import { Route as SuperAuditRouteImport } from './routes/super.audit'
import { Route as CoachSessionsRouteImport } from './routes/coach.sessions'
import { Route as CoachProgramsRouteImport } from './routes/coach.programs'
import { Route as CoachMessagesRouteImport } from './routes/coach.messages'
import { Route as CoachClientsRouteImport } from './routes/coach.clients'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperRoute = SuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const GymsRoute = GymsRouteImport.update({
  id: '/gyms',
  path: '/gyms',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperTenantsRoute = SuperTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSystemRoute = SuperSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => SuperRoute,
} as any)
const SuperFeaturesRoute = SuperFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => SuperRoute,
} as any)
const SuperBillingRoute = SuperBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SuperRoute,
} as any)
const SuperAuditRoute = SuperAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => SuperRoute,
} as any)
const CoachSessionsRoute = CoachSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => CoachRoute,
} as any)
const CoachProgramsRoute = CoachProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => CoachRoute,
} as any)
const CoachMessagesRoute = CoachMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => CoachRoute,
} as any)
const CoachClientsRoute = CoachClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => CoachRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/coach': typeof CoachRouteWithChildren
  '/coaches': typeof CoachesRoute
  '/food': typeof FoodRoute
  '/gyms': typeof GymsRoute
  '/super': typeof SuperRouteWithChildren
  '/users': typeof UsersRoute
  '/coach/clients': typeof CoachClientsRoute
  '/coach/messages': typeof CoachMessagesRoute
  '/coach/programs': typeof CoachProgramsRoute
  '/coach/sessions': typeof CoachSessionsRoute
  '/super/audit': typeof SuperAuditRoute
  '/super/billing': typeof SuperBillingRoute
  '/super/features': typeof SuperFeaturesRoute
  '/super/system': typeof SuperSystemRoute
  '/super/tenants': typeof SuperTenantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/coach': typeof CoachRouteWithChildren
  '/coaches': typeof CoachesRoute
  '/food': typeof FoodRoute
  '/gyms': typeof GymsRoute
  '/super': typeof SuperRouteWithChildren
  '/users': typeof UsersRoute
  '/coach/clients': typeof CoachClientsRoute
  '/coach/messages': typeof CoachMessagesRoute
  '/coach/programs': typeof CoachProgramsRoute
  '/coach/sessions': typeof CoachSessionsRoute
  '/super/audit': typeof SuperAuditRoute
  '/super/billing': typeof SuperBillingRoute
  '/super/features': typeof SuperFeaturesRoute
  '/super/system': typeof SuperSystemRoute
  '/super/tenants': typeof SuperTenantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/coach': typeof CoachRouteWithChildren
  '/coaches': typeof CoachesRoute
  '/food': typeof FoodRoute
  '/gyms': typeof GymsRoute
  '/super': typeof SuperRouteWithChildren
  '/users': typeof UsersRoute
  '/coach/clients': typeof CoachClientsRoute
  '/coach/messages': typeof CoachMessagesRoute
  '/coach/programs': typeof CoachProgramsRoute
  '/coach/sessions': typeof CoachSessionsRoute
  '/super/audit': typeof SuperAuditRoute
  '/super/billing': typeof SuperBillingRoute
  '/super/features': typeof SuperFeaturesRoute
  '/super/system': typeof SuperSystemRoute
  '/super/tenants': typeof SuperTenantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/coach'
    | '/coaches'
    | '/food'
    | '/gyms'
    | '/super'
    | '/users'
    | '/coach/clients'
    | '/coach/messages'
    | '/coach/programs'
    | '/coach/sessions'
    | '/super/audit'
    | '/super/billing'
    | '/super/features'
    | '/super/system'
    | '/super/tenants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/coach'
    | '/coaches'
    | '/food'
    | '/gyms'
    | '/super'
    | '/users'
    | '/coach/clients'
    | '/coach/messages'
    | '/coach/programs'
    | '/coach/sessions'
    | '/super/audit'
    | '/super/billing'
    | '/super/features'
    | '/super/system'
    | '/super/tenants'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/coach'
    | '/coaches'
    | '/food'
    | '/gyms'
    | '/super'
    | '/users'
    | '/coach/clients'
    | '/coach/messages'
    | '/coach/programs'
    | '/coach/sessions'
    | '/super/audit'
    | '/super/billing'
    | '/super/features'
    | '/super/system'
    | '/super/tenants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CoachRoute: typeof CoachRouteWithChildren
  CoachesRoute: typeof CoachesRoute
  FoodRoute: typeof FoodRoute
  GymsRoute: typeof GymsRoute
  SuperRoute: typeof SuperRouteWithChildren
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super': {
      id: '/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gyms': {
      id: '/gyms'
      path: '/gyms'
      fullPath: '/gyms'
      preLoaderRoute: typeof GymsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/tenants': {
      id: '/super/tenants'
      path: '/tenants'
      fullPath: '/super/tenants'
      preLoaderRoute: typeof SuperTenantsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/system': {
      id: '/super/system'
      path: '/system'
      fullPath: '/super/system'
      preLoaderRoute: typeof SuperSystemRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/features': {
      id: '/super/features'
      path: '/features'
      fullPath: '/super/features'
      preLoaderRoute: typeof SuperFeaturesRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/billing': {
      id: '/super/billing'
      path: '/billing'
      fullPath: '/super/billing'
      preLoaderRoute: typeof SuperBillingRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/audit': {
      id: '/super/audit'
      path: '/audit'
      fullPath: '/super/audit'
      preLoaderRoute: typeof SuperAuditRouteImport
      parentRoute: typeof SuperRoute
    }
    '/coach/sessions': {
      id: '/coach/sessions'
      path: '/sessions'
      fullPath: '/coach/sessions'
      preLoaderRoute: typeof CoachSessionsRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/programs': {
      id: '/coach/programs'
      path: '/programs'
      fullPath: '/coach/programs'
      preLoaderRoute: typeof CoachProgramsRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/messages': {
      id: '/coach/messages'
      path: '/messages'
      fullPath: '/coach/messages'
      preLoaderRoute: typeof CoachMessagesRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/clients': {
      id: '/coach/clients'
      path: '/clients'
      fullPath: '/coach/clients'
      preLoaderRoute: typeof CoachClientsRouteImport
      parentRoute: typeof CoachRoute
    }
  }
}

interface CoachRouteChildren {
  CoachClientsRoute: typeof CoachClientsRoute
  CoachMessagesRoute: typeof CoachMessagesRoute
  CoachProgramsRoute: typeof CoachProgramsRoute
  CoachSessionsRoute: typeof CoachSessionsRoute
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachClientsRoute: CoachClientsRoute,
  CoachMessagesRoute: CoachMessagesRoute,
  CoachProgramsRoute: CoachProgramsRoute,
  CoachSessionsRoute: CoachSessionsRoute,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

interface SuperRouteChildren {
  SuperAuditRoute: typeof SuperAuditRoute
  SuperBillingRoute: typeof SuperBillingRoute
  SuperFeaturesRoute: typeof SuperFeaturesRoute
  SuperSystemRoute: typeof SuperSystemRoute
  SuperTenantsRoute: typeof SuperTenantsRoute
}

const SuperRouteChildren: SuperRouteChildren = {
  SuperAuditRoute: SuperAuditRoute,
  SuperBillingRoute: SuperBillingRoute,
  SuperFeaturesRoute: SuperFeaturesRoute,
  SuperSystemRoute: SuperSystemRoute,
  SuperTenantsRoute: SuperTenantsRoute,
}

const SuperRouteWithChildren = SuperRoute._addFileChildren(SuperRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CoachRoute: CoachRouteWithChildren,
  CoachesRoute: CoachesRoute,
  FoodRoute: FoodRoute,
  GymsRoute: GymsRoute,
  SuperRoute: SuperRouteWithChildren,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
